/**
 * Brilliant Academy — Self-Hosted RTMP Streaming Server
 * 
 * This server:
 * 1. Accepts RTMP streams from OBS / Zoom Pro / StreamYard on port 1935
 * 2. Converts RTMP → HLS in real-time (students watch via browser)
 * 3. Records every stream as .mp4 automatically
 * 4. When stream ends: uploads .mp4 to BunnyCDN & notifies your website
 * 
 * Usage:
 *   npm install
 *   cp .env.example .env   (fill in your keys)
 *   npm start
 * 
 * Then in OBS:
 *   Server:     rtmp://YOUR_SERVER_IP:1935/live
 *   Stream Key: (the key generated by your admin panel)
 */

const NodeMediaServer = require('node-media-server');
const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const crypto = require('crypto');

// ─── Configuration ─────────────────────────────────────────────
const RTMP_PORT = parseInt(process.env.RTMP_PORT || '1935');
const HTTP_PORT = parseInt(process.env.HTTP_PORT || '8000');
const MEDIA_ROOT = process.env.MEDIA_ROOT || './media';

// Your Brilliant Academy website URL (Vercel)
const WEBSITE_URL = process.env.WEBSITE_URL || 'https://brilliantacademy.vercel.app';
const CALLBACK_SECRET = process.env.CALLBACK_SECRET || 'change-me-to-a-random-string';

// Bunny CDN credentials
const BUNNY_LIBRARY_ID = process.env.BUNNY_STREAM_LIBRARY_ID || '';
const BUNNY_API_KEY = process.env.BUNNY_STREAM_API_KEY || '';

// Valid stream keys (comma-separated list, or 'any' to allow all)
// These are generated by the admin panel and passed here
const VALID_STREAM_KEYS = (process.env.VALID_STREAM_KEYS || 'any').split(',').map(k => k.trim());

// ─── Ensure media directories exist ────────────────────────────
const hlsDir = path.join(MEDIA_ROOT, 'live');
const recordingsDir = path.join(MEDIA_ROOT, 'recordings');
[hlsDir, recordingsDir].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// ─── Node-Media-Server (RTMP → HLS + Recording) ───────────────
const nmsConfig = {
  rtmp: {
    port: RTMP_PORT,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: HTTP_PORT + 1,  // Internal port for NMS HTTP (we use Express for public)
    mediaroot: MEDIA_ROOT,
    allow_origin: '*'
  },
  trans: {
    ffmpeg: process.env.FFMPEG_PATH || '/usr/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        hls: true,
        hlsFlags: '[hls_time=1:hls_list_size=3:hls_flags=delete_segments+append_list]',
        hlsKeep: false,  // Clean up HLS segments when stream ends
        mp4: true,
        mp4Flags: '[movflags=frag_keyframe+empty_moov]'
      }
    ]
  }
};

const nms = new NodeMediaServer(nmsConfig);

// ─── Stream Lifecycle Events ───────────────────────────────────

// Track active streams
const activeStreams = new Map();

nms.on('prePublish', (id, StreamPath, args) => {
  console.log(`[RTMP] Pre-publish: ${StreamPath} (Session: ${id})`);
  
  // Extract stream key from path: /live/STREAM_KEY
  const parts = StreamPath.split('/');
  const streamKey = parts[parts.length - 1];
  
  // Validate stream key
  if (VALID_STREAM_KEYS[0] !== 'any' && !VALID_STREAM_KEYS.includes(streamKey)) {
    console.log(`[RTMP] ❌ Rejected unauthorized stream key: ${streamKey}`);
    const session = nms.getSession(id);
    if (session) session.reject();
    return;
  }
  
  console.log(`[RTMP] ✅ Accepted stream: ${streamKey}`);
  activeStreams.set(streamKey, { id, startTime: Date.now(), StreamPath });
  
  // Notify website that stream started
  notifyWebsite('stream_started', { streamKey }).catch(err => 
    console.error('[RTMP] Failed to notify website of stream start:', err.message)
  );
});

nms.on('donePublish', (id, StreamPath, args) => {
  console.log(`[RTMP] Stream ended: ${StreamPath}`);
  
  const parts = StreamPath.split('/');
  const streamKey = parts[parts.length - 1];
  
  activeStreams.delete(streamKey);
  
  // Wait a few seconds for ffmpeg to finish writing the .mp4 file
  setTimeout(() => {
    handleStreamEnded(streamKey).catch(err => 
      console.error('[RTMP] Error in post-stream pipeline:', err.message)
    );
  }, 5000);
});

// ─── Post-Stream Pipeline ──────────────────────────────────────

async function handleStreamEnded(streamKey) {
  console.log(`[Pipeline] Starting post-stream pipeline for: ${streamKey}`);
  
  let mp4File = null;
  
  // Search for .mp4 files in possible locations
  const searchDirs = [
    path.join(MEDIA_ROOT, 'live', streamKey),
    path.join(MEDIA_ROOT, streamKey),
    path.join(MEDIA_ROOT, 'live'),
    recordingsDir,
    MEDIA_ROOT
  ];

  const foundFiles = [];
  
  for (const dir of searchDirs) {
    if (fs.existsSync(dir)) {
      try {
        const stat = fs.statSync(dir);
        if (stat.isFile() && (dir.endsWith('.mp4') || dir.endsWith('.flv'))) {
          foundFiles.push(dir);
        } else if (stat.isDirectory()) {
          const files = fs.readdirSync(dir);
          for (const f of files) {
            const fullPath = path.join(dir, f);
            try {
              const fileStat = fs.statSync(fullPath);
              if (fileStat.isFile() && (f.endsWith('.mp4') || f.endsWith('.flv')) && fileStat.size > 1000) {
                // If it matches streamKey or was modified recently (last 15 mins)
                if (f.includes(streamKey) || (Date.now() - fileStat.mtimeMs < 15 * 60 * 1000)) {
                  foundFiles.push(fullPath);
                }
              }
            } catch (e) {}
          }
        }
      } catch (e) {}
    }
  }

  if (foundFiles.length > 0) {
    // Sort by most recently modified
    foundFiles.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
    mp4File = foundFiles[0];
  }
  
  if (!mp4File || !fs.existsSync(mp4File)) {
    console.log(`[Pipeline] ⚠️ No recording found for stream: ${streamKey}`);
    // Still notify website that stream ended (without recording)
    await notifyWebsite('stream_ended', { streamKey, hasRecording: false });
    return;
  }
  
  const fileSize = fs.statSync(mp4File).size;
  console.log(`[Pipeline] Found recording: ${mp4File} (${(fileSize / 1024 / 1024).toFixed(1)} MB)`);
  
  // Upload to BunnyCDN
  let bunnyVideoId = null;
  if (BUNNY_LIBRARY_ID && BUNNY_API_KEY) {
    try {
      bunnyVideoId = await uploadToBunny(mp4File, streamKey);
      console.log(`[Pipeline] ✅ Uploaded to Bunny: ${bunnyVideoId}`);
    } catch (err) {
      console.error(`[Pipeline] ❌ Bunny upload failed:`, err.message);
    }
  } else {
    console.log('[Pipeline] ⚠️ Bunny credentials not configured. Skipping upload.');
  }
  
  // Notify website
  await notifyWebsite('stream_ended', { 
    streamKey, 
    hasRecording: true,
    bunnyVideoId,
    bunnyLibraryId: BUNNY_LIBRARY_ID
  });
  
  // Clean up the recording file after upload
  if (bunnyVideoId) {
    try {
      fs.unlinkSync(mp4File);
      console.log(`[Pipeline] 🧹 Cleaned up local recording: ${mp4File}`);
    } catch (e) {
      console.log(`[Pipeline] Could not delete file: ${e.message}`);
    }
  }
}

// ─── Bunny CDN Upload ──────────────────────────────────────────

async function uploadToBunny(filePath, streamKey) {
  // 1. Create video entry in Bunny
  const createRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos`, {
    method: 'POST',
    headers: {
      'AccessKey': BUNNY_API_KEY,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({ title: `Live Recording - ${streamKey} - ${new Date().toISOString().split('T')[0]}` })
  });
  
  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Bunny create failed: ${errText}`);
  }
  
  const videoData = await createRes.json();
  const videoId = videoData.guid;
  
  console.log(`[Bunny] Created video: ${videoId}. Starting upload...`);
  
  // 2. Upload the file (support Stream with fallback to Buffer)
  const stats = fs.statSync(filePath);
  
  try {
    const fileStream = fs.createReadStream(filePath);
    const uploadRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
      method: 'PUT',
      headers: {
        'AccessKey': BUNNY_API_KEY,
        'Content-Type': 'application/octet-stream',
        'Content-Length': stats.size.toString()
      },
      body: fileStream,
      duplex: 'half'
    });
    
    if (uploadRes.ok) {
      console.log(`[Bunny] ✅ Upload complete for video: ${videoId}`);
      return videoId;
    }
  } catch (streamErr) {
    console.warn(`[Bunny] Stream upload error, retrying with buffer fallback:`, streamErr.message);
  }

  // Buffer Fallback
  const fileBuffer = fs.readFileSync(filePath);
  const uploadRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
    method: 'PUT',
    headers: {
      'AccessKey': BUNNY_API_KEY,
      'Content-Type': 'application/octet-stream',
      'Content-Length': fileBuffer.length.toString()
    },
    body: fileBuffer
  });

  if (!uploadRes.ok) {
    const errText = await uploadRes.text();
    throw new Error(`Bunny upload failed: ${errText}`);
  }

  console.log(`[Bunny] ✅ Upload complete (via buffer) for video: ${videoId}`);
  return videoId;
}

// ─── Website Callback ──────────────────────────────────────────

async function notifyWebsite(event, data) {
  const payload = { event, ...data, secret: CALLBACK_SECRET };
  
  console.log(`[Callback] Notifying website: ${event}`);
  
  const res = await fetch(`${WEBSITE_URL}/api/live/rtmp-callback`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });
  
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Website callback failed (${res.status}): ${text}`);
  }
  
  console.log(`[Callback] ✅ Website notified successfully`);
}

// ─── Express API (Status + HLS Serving) ────────────────────────

const app = express();
app.use(cors());
app.use(express.json());

// Serve HLS files with correct MIME types
app.use('/live', express.static(path.join(MEDIA_ROOT, 'live'), {
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.m3u8')) {
      res.setHeader('Content-Type', 'application/vnd.apple.mpegurl');
      res.setHeader('Cache-Control', 'no-cache, no-store');
    } else if (filePath.endsWith('.ts')) {
      res.setHeader('Content-Type', 'video/MP2T');
    }
  }
}));

// Health check
app.get('/status', (req, res) => {
  res.json({
    status: 'ok',
    activeStreams: Array.from(activeStreams.keys()),
    uptime: process.uptime()
  });
});

// Check if a specific stream is live
app.get('/stream/:streamKey/status', (req, res) => {
  const { streamKey } = req.params;
  const stream = activeStreams.get(streamKey);
  
  if (stream) {
    res.json({
      live: true,
      streamKey,
      startTime: stream.startTime,
      hlsUrl: `/live/${streamKey}/index.m3u8`,
      duration: Math.floor((Date.now() - stream.startTime) / 1000)
    });
  } else {
    res.json({ live: false, streamKey });
  }
});

// Generate a new stream key (called by admin panel)
app.post('/generate-key', (req, res) => {
  const { secret } = req.body;
  
  if (secret !== CALLBACK_SECRET) {
    return res.status(403).json({ error: 'Invalid secret' });
  }
  
  const streamKey = 'ba_' + crypto.randomBytes(12).toString('hex');
  
  // Add to valid keys (runtime only — for persistent keys, update .env)
  if (VALID_STREAM_KEYS[0] !== 'any') {
    VALID_STREAM_KEYS.push(streamKey);
  }
  
  res.json({
    streamKey,
    rtmpUrl: `rtmp://${process.env.SERVER_HOST || 'YOUR_SERVER_IP'}:${RTMP_PORT}/live`,
    hlsUrl: `http://${process.env.SERVER_HOST || 'YOUR_SERVER_IP'}:${HTTP_PORT}/live/${streamKey}/index.m3u8`
  });
});

// Download from YouTube/Zoom and push to Bunny
app.post('/api/convert-youtube', (req, res) => {
  const { secret, url, streamKey, password } = req.body;
  
  if (secret !== CALLBACK_SECRET) {
    return res.status(403).json({ error: 'Invalid secret' });
  }
  if (!url || !streamKey) {
    return res.status(400).json({ error: 'Missing url or streamKey' });
  }

  console.log(`[Downloader] Received download request for ${streamKey}: ${url}`);
  
  // Respond immediately so Vercel doesn't time out
  res.json({ success: true, message: 'Download started in background' });

  // Run yt-dlp in background
  const { spawn } = require('child_process');
  const outputPath = path.join(recordingsDir, `${streamKey}_download.mp4`);
  
  // Base yt-dlp args
  const args = [
    '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
    '-o', outputPath
  ];
  
  // Add password if provided (for Zoom, Vimeo, etc)
  if (password) {
    args.push('--video-password', password);
  }
  
  args.push(url);

  const ytdlp = spawn('yt-dlp', args);

  ytdlp.stdout.on('data', (data) => console.log(`[yt-dlp] ${data.toString().trim()}`));
  ytdlp.stderr.on('data', (data) => console.error(`[yt-dlp] ${data.toString().trim()}`));

  ytdlp.on('close', (code) => {
    if (code === 0) {
      console.log(`[Downloader] ✅ Download complete for ${streamKey}`);
      // Trigger the existing post-stream pipeline to upload to Bunny and notify website
      handleStreamEnded(streamKey).catch(err => 
        console.error('[Downloader] Error in post-stream pipeline:', err.message)
      );
    } else {
      console.error(`[Downloader] ❌ yt-dlp process exited with code ${code}`);
      notifyWebsite('stream_ended', { streamKey, hasRecording: false }).catch(() => {});
    }
  });
});

// Generic Downloader for Admin Dashboard
// Handles YouTube (with bot-bypass) and Zoom separately
app.post('/api/generic-download', (req, res) => {
  const { secret, url, password, title, metadata, webhookUrl } = req.body;
  if (secret !== CALLBACK_SECRET) return res.status(403).json({ error: 'Invalid secret' });

  res.json({ success: true, message: 'Generic download started' });

  const { spawn } = require('child_process');
  const jobId = crypto.randomBytes(8).toString('hex');
  const outputPath = path.join(recordingsDir, `generic_${jobId}.mp4`);

  const isYoutube = url.includes('youtube.com') || url.includes('youtu.be');

  let args = [];

  if (isYoutube) {
    // ─── YouTube: Full Bot-Bypass Configuration ───────────────────
    console.log(`[Generic] 🎬 YouTube URL detected - using bot-bypass mode`);

    // Check if Cloudflare WARP proxy is available (installed via setup.sh)
    const warpProxy = process.env.WARP_PROXY || 'socks5://127.0.0.1:40000';
    const cookiesPath = process.env.YT_COOKIES_PATH || '/opt/brilliant-academy-rtmp/cookies.txt';
    const cookiesExist = fs.existsSync(cookiesPath);

    args = [
      // 1. Route through Cloudflare WARP to avoid AWS IP block
      '--proxy', warpProxy,

      // 2. Pretend to be the YouTube Android app (less bot detection)
      '--extractor-args', 'youtube:player_client=android,web',

      // 3. Use cookies if available (burner account login to bypass bot checks)
      ...(cookiesExist ? ['--cookies', cookiesPath] : []),

      // 4. Throttle speed to avoid triggering bot alarms (5 MB/s = realistic)
      '--limit-rate', '5M',

      // 5. Best quality up to 720p (good quality, smaller file for faster transfer)
      '--format', 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/bestvideo[height<=720]+bestaudio/best[height<=720]/best',
      '--merge-output-format', 'mp4',

      // 6. Retry on failure (YouTube sometimes blocks first attempt)
      '--retries', '5',
      '--fragment-retries', '5',

      // 7. Add headers to look like a real browser
      '--add-header', 'Accept-Language:en-US,en;q=0.9',

      '-o', outputPath,
      url
    ];

    if (!cookiesExist) {
      console.log(`[Generic] ⚠️  No cookies.txt found at ${cookiesPath}. Downloads may fail for some videos. See setup instructions.`);
    }
  } else {
    // ─── Zoom / Other URLs: Standard Download ─────────────────────
    console.log(`[Generic] 📹 Non-YouTube URL detected - using standard mode`);
    args = [
      '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
      '--merge-output-format', 'mp4',
      '--retries', '3',
      '-o', outputPath
    ];
    if (password) args.push('--video-password', password);
    args.push(url);
  }

  console.log(`[Generic] Running yt-dlp for: ${title}`);
  const ytdlp = spawn('yt-dlp', args);

  ytdlp.stdout.on('data', (data) => console.log(`[yt-dlp] ${data.toString().trim()}`));
  ytdlp.stderr.on('data', (data) => console.error(`[yt-dlp stderr] ${data.toString().trim()}`));

  ytdlp.on('close', async (code) => {
    if (code === 0 && fs.existsSync(outputPath)) {
      try {
        const fileSizeMB = (fs.statSync(outputPath).size / 1024 / 1024).toFixed(1);
        console.log(`[Generic] ✅ Download complete for "${title}" (${fileSizeMB} MB)`);

        // Upload to Bunny using streaming (better for large files)
        console.log(`[Generic] Uploading to BunnyCDN...`);
        const createRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos`, {
          method: 'POST',
          headers: { 'AccessKey': BUNNY_API_KEY, 'Content-Type': 'application/json', 'Accept': 'application/json' },
          body: JSON.stringify({ title: title || 'Downloaded Video' })
        });

        if (!createRes.ok) throw new Error(`Bunny create failed: ${await createRes.text()}`);
        const videoData = await createRes.json();
        const videoId = videoData.guid;

        // Stream upload (handles large files without loading into memory)
        const fileStats = fs.statSync(outputPath);
        let uploadOk = false;
        try {
          const fileStream = fs.createReadStream(outputPath);
          const uploadRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
            method: 'PUT',
            headers: {
              'AccessKey': BUNNY_API_KEY,
              'Content-Type': 'application/octet-stream',
              'Content-Length': fileStats.size.toString()
            },
            body: fileStream,
            duplex: 'half'
          });
          uploadOk = uploadRes.ok;
          if (!uploadOk) console.error(`[Generic] Stream upload failed: ${await uploadRes.text()}`);
        } catch (streamErr) {
          console.warn(`[Generic] Stream upload failed, falling back to buffer: ${streamErr.message}`);
        }

        // Buffer fallback for small files
        if (!uploadOk) {
          const fileBuffer = fs.readFileSync(outputPath);
          const uploadRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
            method: 'PUT',
            headers: {
              'AccessKey': BUNNY_API_KEY,
              'Content-Type': 'application/octet-stream',
              'Content-Length': fileBuffer.length.toString()
            },
            body: fileBuffer
          });
          if (!uploadRes.ok) throw new Error(`Bunny upload failed: ${await uploadRes.text()}`);
        }

        console.log(`[Generic] ✅ Uploaded to Bunny: ${videoId} for "${title}"`);

        // Notify Vercel webhook
        if (webhookUrl) {
          await fetch(webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ secret: CALLBACK_SECRET, videoId, metadata, libraryId: BUNNY_LIBRARY_ID })
          });
          console.log(`[Generic] ✅ Notified webhook for "${title}"`);
        }

        // Clean up temp file
        try { fs.unlinkSync(outputPath); } catch (e) {}
      } catch (err) {
        console.error(`[Generic] ❌ Upload/notify failed for "${title}":`, err.message);
      }
    } else {
      console.error(`[Generic] ❌ yt-dlp failed with code ${code} for "${title}"`);
      // Notify webhook of failure so frontend can update status
      if (webhookUrl && metadata) {
        try {
          await fetch(webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ secret: CALLBACK_SECRET, error: 'yt-dlp download failed', metadata, libraryId: BUNNY_LIBRARY_ID })
          });
        } catch (e) {}
      }
    }
  });
});

// ─── Auto Disk Cleanup (Safety Net) ───────────────────────────
// Deletes any leftover temp files older than 2 hours every 60 minutes.
// This protects the disk if the server crashes mid-upload.

const TEMP_FILE_MAX_AGE_MS = parseInt(process.env.TEMP_FILE_MAX_AGE_HOURS || '2') * 60 * 60 * 1000;
const DISK_WARN_PERCENT    = parseInt(process.env.DISK_WARN_PERCENT || '80');

function cleanOldTempFiles() {
  const now = Date.now();
  let deletedCount = 0;
  let freedBytes = 0;

  const dirsToClean = [recordingsDir, path.join(MEDIA_ROOT, 'live')];

  for (const dir of dirsToClean) {
    if (!fs.existsSync(dir)) continue;
    try {
      const entries = fs.readdirSync(dir);
      for (const entry of entries) {
        const fullPath = path.join(dir, entry);
        try {
          const stat = fs.statSync(fullPath);
          // Only delete video/temp files older than max age
          const isVideoFile = /\.(mp4|mkv|webm|flv|m4a|part|ytdl)$/i.test(entry);
          const isOld = (now - stat.mtimeMs) > TEMP_FILE_MAX_AGE_MS;
          if (stat.isFile() && isVideoFile && isOld) {
            freedBytes += stat.size;
            fs.unlinkSync(fullPath);
            deletedCount++;
            console.log(`[Cleanup] 🗑️  Deleted old temp file: ${entry} (${(stat.size / 1024 / 1024).toFixed(1)} MB)`);
          }
        } catch (e) { /* skip locked files */ }
      }
    } catch (e) { /* skip unreadable dirs */ }
  }

  if (deletedCount > 0) {
    console.log(`[Cleanup] ✅ Cleaned ${deletedCount} file(s), freed ${(freedBytes / 1024 / 1024).toFixed(1)} MB`);
  }
}

function checkDiskSpace() {
  const { execSync } = require('child_process');
  try {
    // Get disk usage percentage for /
    const output = execSync("df / | tail -1 | awk '{print $5}'").toString().trim().replace('%', '');
    const usedPercent = parseInt(output);
    if (usedPercent >= DISK_WARN_PERCENT) {
      console.warn(`[Disk] ⚠️  WARNING: Disk is ${usedPercent}% full! Running emergency cleanup...`);
      cleanOldTempFiles();

      // If still critical (>90%), also delete HLS segments
      const output2 = execSync("df / | tail -1 | awk '{print $5}'").toString().trim().replace('%', '');
      if (parseInt(output2) >= 90) {
        console.warn(`[Disk] 🚨 CRITICAL: Disk still ${output2}% full. Clearing ALL HLS segments...`);
        try {
          execSync(`find ${path.join(MEDIA_ROOT, 'live')} -name "*.ts" -delete`);
          execSync(`find ${path.join(MEDIA_ROOT, 'live')} -name "*.m3u8" -delete`);
          console.warn(`[Disk] Cleared HLS segments to protect disk.`);
        } catch (e) {}
      }
    } else {
      console.log(`[Disk] ✅ Disk health: ${usedPercent}% used`);
    }
  } catch (e) {
    console.error('[Disk] Could not check disk space:', e.message);
  }
}

// Run cleanup every 60 minutes
const CLEANUP_INTERVAL_MS = 60 * 60 * 1000; // 1 hour
setInterval(() => {
  console.log(`[Cleanup] ⏱️  Running scheduled disk cleanup (every 1 hour)...`);
  cleanOldTempFiles();
  checkDiskSpace();
}, CLEANUP_INTERVAL_MS);

// Also run once on startup (to clean any leftovers from previous crash)
setTimeout(() => {
  console.log(`[Cleanup] 🚀 Running startup disk cleanup...`);
  cleanOldTempFiles();
  checkDiskSpace();
}, 10000); // 10 seconds after start

// ─── Start Everything ──────────────────────────────────────────

app.listen(HTTP_PORT, () => {
  console.log(`\n🌐 HTTP/HLS Server running on port ${HTTP_PORT}`);
  console.log(`   HLS URL pattern: http://YOUR_SERVER:${HTTP_PORT}/live/STREAM_KEY/index.m3u8`);
  console.log(`   Status: http://YOUR_SERVER:${HTTP_PORT}/status`);
  console.log(`   Auto-cleanup: deletes temp files older than ${TEMP_FILE_MAX_AGE_MS / 3600000}h every 1h`);
});

nms.run();
console.log(`\n📡 RTMP Server running on port ${RTMP_PORT}`);
console.log(`   RTMP URL: rtmp://YOUR_SERVER:${RTMP_PORT}/live`);
console.log(`\n✅ Brilliant Academy Streaming Server is ready!\n`);
console.log(`   To stream from OBS:`);
console.log(`   Server:     rtmp://YOUR_SERVER_IP:${RTMP_PORT}/live`);
console.log(`   Stream Key: (generated by admin panel)\n`);

