/**
 * Brilliant Academy — Self-Hosted RTMP Streaming Server
 * 
 * This server:
 * 1. Accepts RTMP streams from OBS / Zoom Pro / StreamYard on port 1935
 * 2. Converts RTMP → HLS in real-time (students watch via browser)
 * 3. Records every stream as .mp4 automatically
 * 4. When stream ends: uploads .mp4 to BunnyCDN & notifies your website
 * 
 * Usage:
 *   npm install
 *   cp .env.example .env   (fill in your keys)
 *   npm start
 * 
 * Then in OBS:
 *   Server:     rtmp://YOUR_SERVER_IP:1935/live
 *   Stream Key: (the key generated by your admin panel)
 */

const NodeMediaServer = require('node-media-server');
const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const crypto = require('crypto');

// ─── Configuration ─────────────────────────────────────────────
const RTMP_PORT = parseInt(process.env.RTMP_PORT || '1935');
const HTTP_PORT = parseInt(process.env.HTTP_PORT || '8000');
const MEDIA_ROOT = process.env.MEDIA_ROOT || './media';

// Your Brilliant Academy website URL (Vercel)
const WEBSITE_URL = process.env.WEBSITE_URL || 'https://brilliantacademy.vercel.app';
const CALLBACK_SECRET = process.env.CALLBACK_SECRET || 'change-me-to-a-random-string';

// Bunny CDN credentials
const BUNNY_LIBRARY_ID = process.env.BUNNY_STREAM_LIBRARY_ID || '';
const BUNNY_API_KEY = process.env.BUNNY_STREAM_API_KEY || '';

// Valid stream keys (comma-separated list, or 'any' to allow all)
// These are generated by the admin panel and passed here
const VALID_STREAM_KEYS = (process.env.VALID_STREAM_KEYS || 'any').split(',').map(k => k.trim());

// ─── Ensure media directories exist ────────────────────────────
const hlsDir = path.join(MEDIA_ROOT, 'live');
const recordingsDir = path.join(MEDIA_ROOT, 'recordings');
[hlsDir, recordingsDir].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// ─── Node-Media-Server (RTMP → HLS + Recording) ───────────────
const nmsConfig = {
  rtmp: {
    port: RTMP_PORT,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: HTTP_PORT + 1,  // Internal port for NMS HTTP (we use Express for public)
    mediaroot: MEDIA_ROOT,
    allow_origin: '*'
  },
  trans: {
    ffmpeg: process.env.FFMPEG_PATH || '/usr/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        hls: true,
        hlsFlags: '[hls_time=1:hls_list_size=3:hls_flags=delete_segments+append_list]',
        hlsKeep: false,  // Clean up HLS segments when stream ends
        mp4: true,
        mp4Flags: '[movflags=frag_keyframe+empty_moov]'
      }
    ]
  }
};

const nms = new NodeMediaServer(nmsConfig);

// ─── Stream Lifecycle Events ───────────────────────────────────

// Track active streams
const activeStreams = new Map();

nms.on('prePublish', (id, StreamPath, args) => {
  console.log(`[RTMP] Pre-publish: ${StreamPath} (Session: ${id})`);
  
  // Extract stream key from path: /live/STREAM_KEY
  const parts = StreamPath.split('/');
  const streamKey = parts[parts.length - 1];
  
  // Validate stream key
  if (VALID_STREAM_KEYS[0] !== 'any' && !VALID_STREAM_KEYS.includes(streamKey)) {
    console.log(`[RTMP] ❌ Rejected unauthorized stream key: ${streamKey}`);
    const session = nms.getSession(id);
    if (session) session.reject();
    return;
  }
  
  console.log(`[RTMP] ✅ Accepted stream: ${streamKey}`);
  activeStreams.set(streamKey, { id, startTime: Date.now(), StreamPath });
  
  // Notify website that stream started
  notifyWebsite('stream_started', { streamKey }).catch(err => 
    console.error('[RTMP] Failed to notify website of stream start:', err.message)
  );
});

nms.on('donePublish', (id, StreamPath, args) => {
  console.log(`[RTMP] Stream ended: ${StreamPath}`);
  
  const parts = StreamPath.split('/');
  const streamKey = parts[parts.length - 1];
  
  activeStreams.delete(streamKey);
  
  // Wait a few seconds for ffmpeg to finish writing the .mp4 file
  setTimeout(() => {
    handleStreamEnded(streamKey).catch(err => 
      console.error('[RTMP] Error in post-stream pipeline:', err.message)
    );
  }, 5000);
});

// ─── Post-Stream Pipeline ──────────────────────────────────────

async function handleStreamEnded(streamKey) {
  console.log(`[Pipeline] Starting post-stream pipeline for: ${streamKey}`);
  
  // Find the recorded .mp4 file
  const mp4Dir = path.join(recordingsDir);
  const mp4Path = path.join(MEDIA_ROOT, 'live', streamKey);
  
  // Node-Media-Server saves recordings in media/live/STREAM_KEY/
  // The .mp4 file is inside that folder
  let mp4File = null;
  
  // Search for .mp4 files in possible locations
  const searchDirs = [
    path.join(MEDIA_ROOT, 'live', streamKey),
    path.join(MEDIA_ROOT, streamKey),
    recordingsDir
  ];
  
  for (const dir of searchDirs) {
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir).filter(f => f.endsWith('.mp4'));
      if (files.length > 0) {
        // Get the most recent .mp4 file
        files.sort((a, b) => {
          const statA = fs.statSync(path.join(dir, a));
          const statB = fs.statSync(path.join(dir, b));
          return statB.mtimeMs - statA.mtimeMs;
        });
        mp4File = path.join(dir, files[0]);
        break;
      }
    }
  }
  
  if (!mp4File || !fs.existsSync(mp4File)) {
    console.log(`[Pipeline] ⚠️ No recording found for stream: ${streamKey}`);
    // Still notify website that stream ended (without recording)
    await notifyWebsite('stream_ended', { streamKey, hasRecording: false });
    return;
  }
  
  const fileSize = fs.statSync(mp4File).size;
  console.log(`[Pipeline] Found recording: ${mp4File} (${(fileSize / 1024 / 1024).toFixed(1)} MB)`);
  
  // Upload to BunnyCDN
  let bunnyVideoId = null;
  if (BUNNY_LIBRARY_ID && BUNNY_API_KEY) {
    try {
      bunnyVideoId = await uploadToBunny(mp4File, streamKey);
      console.log(`[Pipeline] ✅ Uploaded to Bunny: ${bunnyVideoId}`);
    } catch (err) {
      console.error(`[Pipeline] ❌ Bunny upload failed:`, err.message);
    }
  } else {
    console.log('[Pipeline] ⚠️ Bunny credentials not configured. Skipping upload.');
  }
  
  // Notify website
  await notifyWebsite('stream_ended', { 
    streamKey, 
    hasRecording: true,
    bunnyVideoId,
    bunnyLibraryId: BUNNY_LIBRARY_ID
  });
  
  // Clean up the recording file after upload
  if (bunnyVideoId) {
    try {
      fs.unlinkSync(mp4File);
      console.log(`[Pipeline] 🧹 Cleaned up local recording: ${mp4File}`);
    } catch (e) {
      console.log(`[Pipeline] Could not delete file: ${e.message}`);
    }
  }
}

// ─── Bunny CDN Upload ──────────────────────────────────────────

async function uploadToBunny(filePath, streamKey) {
  // 1. Create video entry in Bunny
  const createRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos`, {
    method: 'POST',
    headers: {
      'AccessKey': BUNNY_API_KEY,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({ title: `Live Recording - ${streamKey} - ${new Date().toISOString().split('T')[0]}` })
  });
  
  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Bunny create failed: ${errText}`);
  }
  
  const videoData = await createRes.json();
  const videoId = videoData.guid;
  
  console.log(`[Bunny] Created video: ${videoId}. Starting upload...`);
  
  // 2. Upload the .mp4 file
  const fileStream = fs.createReadStream(filePath);
  const stats = fs.statSync(filePath);
  
  const uploadRes = await fetch(`https://video.bunnycdn.com/library/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
    method: 'PUT',
    headers: {
      'AccessKey': BUNNY_API_KEY,
      'Content-Type': 'application/octet-stream',
      'Content-Length': stats.size.toString()
    },
    body: fileStream,
    duplex: 'half'
  });
  
  if (!uploadRes.ok) {
    const errText = await uploadRes.text();
    throw new Error(`Bunny upload failed: ${errText}`);
  }
  
  console.log(`[Bunny] ✅ Upload complete for video: ${videoId}`);
  return videoId;
}

// ─── Website Callback ──────────────────────────────────────────

async function notifyWebsite(event, data) {
  const payload = { event, ...data, secret: CALLBACK_SECRET };
  
  console.log(`[Callback] Notifying website: ${event}`);
  
  const res = await fetch(`${WEBSITE_URL}/api/live/rtmp-callback`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });
  
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Website callback failed (${res.status}): ${text}`);
  }
  
  console.log(`[Callback] ✅ Website notified successfully`);
}

// ─── Express API (Status + HLS Serving) ────────────────────────

const app = express();
app.use(cors());
app.use(express.json());

// Serve HLS files with correct MIME types
app.use('/live', express.static(path.join(MEDIA_ROOT, 'live'), {
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.m3u8')) {
      res.setHeader('Content-Type', 'application/vnd.apple.mpegurl');
      res.setHeader('Cache-Control', 'no-cache, no-store');
    } else if (filePath.endsWith('.ts')) {
      res.setHeader('Content-Type', 'video/MP2T');
    }
  }
}));

// Health check
app.get('/status', (req, res) => {
  res.json({
    status: 'ok',
    activeStreams: Array.from(activeStreams.keys()),
    uptime: process.uptime()
  });
});

// Check if a specific stream is live
app.get('/stream/:streamKey/status', (req, res) => {
  const { streamKey } = req.params;
  const stream = activeStreams.get(streamKey);
  
  if (stream) {
    res.json({
      live: true,
      streamKey,
      startTime: stream.startTime,
      hlsUrl: `/live/${streamKey}/index.m3u8`,
      duration: Math.floor((Date.now() - stream.startTime) / 1000)
    });
  } else {
    res.json({ live: false, streamKey });
  }
});

// Generate a new stream key (called by admin panel)
app.post('/generate-key', (req, res) => {
  const { secret } = req.body;
  
  if (secret !== CALLBACK_SECRET) {
    return res.status(403).json({ error: 'Invalid secret' });
  }
  
  const streamKey = 'ba_' + crypto.randomBytes(12).toString('hex');
  
  // Add to valid keys (runtime only — for persistent keys, update .env)
  if (VALID_STREAM_KEYS[0] !== 'any') {
    VALID_STREAM_KEYS.push(streamKey);
  }
  
  res.json({
    streamKey,
    rtmpUrl: `rtmp://${process.env.SERVER_HOST || 'YOUR_SERVER_IP'}:${RTMP_PORT}/live`,
    hlsUrl: `http://${process.env.SERVER_HOST || 'YOUR_SERVER_IP'}:${HTTP_PORT}/live/${streamKey}/index.m3u8`
  });
});

// ─── Start Everything ──────────────────────────────────────────

app.listen(HTTP_PORT, () => {
  console.log(`\n🌐 HTTP/HLS Server running on port ${HTTP_PORT}`);
  console.log(`   HLS URL pattern: http://YOUR_SERVER:${HTTP_PORT}/live/STREAM_KEY/index.m3u8`);
  console.log(`   Status: http://YOUR_SERVER:${HTTP_PORT}/status`);
});

nms.run();
console.log(`\n📡 RTMP Server running on port ${RTMP_PORT}`);
console.log(`   RTMP URL: rtmp://YOUR_SERVER:${RTMP_PORT}/live`);
console.log(`\n✅ Brilliant Academy Streaming Server is ready!\n`);
console.log(`   To stream from OBS:`);
console.log(`   Server:     rtmp://YOUR_SERVER_IP:${RTMP_PORT}/live`);
console.log(`   Stream Key: (generated by admin panel)\n`);
